name: "Custom action using docker"
description: "Using docker out of 3 (composite, javascript, composite)"
inputs:
  bucket:
    description: "The name of the bucket"
  bucket-region:
    description: "The region of the bucket"
  dist-folder:
    description: "The folder that has deployable files"
outputs:
  website-url:
    description: "Live website url"
runs:
  using: docker
  image: "Dockerfile"
